name: CI/CD with SpecFlow LivingDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-generate-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Run tests and generate TestExecution.xml
      run: dotnet test --no-build --results-directory ./TestResults --logger "nunit;LogFilePath=TestResults/TestExecution.xml"

    - name: Install SpecFlow Plus LivingDoc CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

    - name: Generate SpecFlow LivingDoc with test results
      run: |
        livingdoc test-assembly BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0/BDD.AcceptanceTests.SpecFlow.dll -t TestResults/TestExecution.xml -o LivingDoc.html

    - name: Rename LivingDoc.html to index.html
      run: mv LivingDoc.html index.html

    - name: Checkout LivingDoc branch
      run: |
        git fetch
        git checkout LivingDoc || git checkout -b LivingDoc
        git reset --hard origin/LivingDoc || true

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and Push index.html
      run: |
        git add index.html
        git commit -m "Update SpecFlow Living Documentation" || echo "No changes to commit"
        git push -f origin LivingDoc
