name: CI/CD with SpecFlow LivingDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-generate-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build

    - name: Install SpecFlow Plus LivingDoc CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

    - name: Generate SpecFlow LivingDoc
      run: livingdoc test-assembly BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0/BDD.AcceptanceTests.SpecFlow.dll -t BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0/TestExecution.json -o LivingDoc.html

    - name: Clone repository in a new directory
      run: |
        git clone https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} ../repo-temp

    - name: Configure Git and commit the documentation
      run: |
        cd ../repo-temp
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout --orphan new-branch
        mv ../${{ github.workspace }}/LivingDoc.html .
        git add LivingDoc.html
        git commit -m "Update SpecFlow Living Documentation"

    - name: Force push to LivingDoc branch
      run: |
        cd ../repo-temp
        git push -f origin HEAD:LivingDoc
