name: CI/CD with SpecFlow LivingDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-generate-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        fetch-depth: 0  # Ensure all history is fetched

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build

    - name: Install SpecFlow Plus LivingDoc CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

    - name: Generate SpecFlow LivingDoc
      run: |
        livingdoc test-assembly BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0/BDD.AcceptanceTests.SpecFlow.dll -o LivingDoc.html

    - name: Checkout LivingDoc branch
      run: |
        git fetch
        git checkout LivingDoc || git checkout -b LivingDoc
        git reset --hard origin/LivingDoc || true  # Reset local branch to match remote

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and Push LivingDoc.html
      run: |
        git add LivingDoc.html
        git commit -m "Update SpecFlow Living Documentation" || echo "No changes to commit"
        git push -f origin LivingDoc
