name: Generate and Commit bin Folder

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-commit-bin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures the entire history is available for the push

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Specify the .NET version used in your project

    - name: Restore dependencies
      run: dotnet restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Build
      run: dotnet build --no-restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Commit bin folder
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f BDD.AcceptanceTests.SpecFlow/bin/
        git commit -m "Add bin folder"
        git push
