name: .NET CI with SpecFlow LivingDoc and Debugging

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x  # Match this with your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Debug: List contents after build
      run: ls -lR

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Debug: List contents after test
      run: ls -lR

    - name: Install LivingDoc CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

    - name: Debug: List contents before LivingDoc generation
      run: ls -lR

    - name: Generate Living Documentation
      run: |
        cd BDD-Tests/BDD/BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0
        livingdoc test-assembly BDD.AcceptanceTests.SpecFlow.dll -t TestExecution.json
