name: Generate, Commit, and Deploy Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Build
      run: dotnet build --no-restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Generate SpecFlow Living Documentation
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0/BDD.AcceptanceTests.SpecFlow.dll -t TestExecution.json -o livingdoc.html

    - name: Commit and Push Documentation to Documentation Branch
      run: |
        git checkout -b documentation || git checkout documentation
        git pull origin documentation || true
        git add livingdoc.html
        git commit -m "Update Living Documentation"
        git push origin documentation
