name: Update bin Folder in Documentation Branch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-bin-folder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the PAT for checkout

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Specify the .NET version used in your project

    - name: Restore dependencies
      run: dotnet restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Build
      run: dotnet build --no-restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Checkout Documentation branch
      run: git checkout -b Documentation || git checkout Documentation

    - name: Remove old bin content
      run: rm -rf bin/ || true

    - name: Copy new bin folder
      run: cp -r BDD.AcceptanceTests.SpecFlow/bin .

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f bin/
        git commit -m "Update bin folder from BDD.AcceptanceTests.SpecFlow"
        git push --set-upstream origin Documentation --force
