name: Build SpecFlow Test Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'  # Adjust to match your project's .NET version

    - name: Restore dependencies for the test project
      run: dotnet restore BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj

    - name: Build the test project
      run: dotnet build BDD.AcceptanceTests.SpecFlow/BDD.AcceptanceTests.SpecFlow.csproj --no-restore
