name: CI/CD with SpecFlow LivingDoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-generate-doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        fetch-depth: 0  

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Change directory to test assembly location
      run: cd BDD.AcceptanceTests.SpecFlow/bin/Debug/net7.0

    - name: Generate SpecFlow LivingDoc
      run: livingdoc test-assembly BDD.AcceptanceTests.SpecFlow.dll -t TestExecution.json -o LivingDoc.html
